### ISSUE TITLE
Clean Up Repo

### ISSUE THREAD

**Issue by joegasewicz** [joegasewicz/flask-jwt-router#157]
Clean up docs, remove requirements.txt, general clean up of repo...

**Comment by fre-sch** [comment]
Does this ticket include code cleanups, such as changes to cumbersome and unpythonic code?

Example a number of minor bad practices in `flask_jwt_router/_config.py`:
```python
def init_config(...):
```
Having methods named `init_XYZ` indicates those are the actual constructor, especially if there's no/empty `def __init__()`. Having multiple `init_XYZ` methods indicates using a Factory pattern or `@classmethod`s to create instances could be appropriate.

```python
self.entity_key = app_config.get("ENTITY_KEY") or "id"
```
The `get` method of dictionary already handles default values if keys are missing. In this case the intention seems to be "key is missing or ~~empty~~ _falsy_ use default". However this intention of using `or` here will fail if key `ENTITY_KEY` is set to something considered truthy (consider `ENTITY_KEY = 1`).

```python
self.google_oauth = kwargs.get("google_oauth")
```
KW args are already considered optional and should be part of the signature. Since `get` will already default to `None`, there's no issue here to include it in the signature as `google_oauth: Dict = None`. Same for `entity_models`.

```python
def init_config(self, app_config: Dict[str, Any], google_oauth: Dict = None, entity_models: List[_ORMType] = []) -> None:
```

**Comment by fre-sch** [comment]
Just to clarify on the `init_xyz` topic:

`Config` is used in `_jwt_routes.py:239`:

```python
class JwtRoutes:
  def __init__(...):
    self.config = Config()
```

At this point, `self.config` could be left `None`, until `JwtRoutes.init_app(...)` can provide the extra parameters:

```python
    #self.config.init_config(app_config, entity_models=entity_models, google_oauth=self.google_oauth)
    self.config = Config(app_config, entity_models=entity_models, google_oauth=self.google_oauth)
```

 There's no usage of `self.config` between `_jwt_routes.py:239` and `JwtRoutes.init_app(...)` (they are within the same execution context `JwtRoutes.__init__(...)`), so there's no need to keep this unconfigured object around.
 
Considering that `JwtRoutes.init_app(...)` could also be called outside of `JwtRoutes.__init__(...)`, the suggestion would still work since `Config` is essentially completely reinitialized. Even more so, creating new `Config` instance in `JwtRoutes.init_app(...)` indicates this complete reinitialization more clearly.

**Comment by joegasewicz** [comment]
@fre-sch  no this doesn't. Clean up repo has nothing to do with rewriting tested and working code for no real reason.

I'm assigning this issue to myself so there is no further confusion with this issue,
thanks
